version: '3.5'

services:
  adminer:
    image: adminer
    container_name: debug_adminer
    ports:
      - "9000:8080"
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:10
    container_name: debug_postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
